services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: college
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./college-backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/college
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

  frontend:
    build:
      context: ./college-frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
